{"name": "Система вернёт ошибку, если в данных запроса указать неправильно логин или пароль", "status": "failed", "statusDetails": {"message": "AssertionError: assert (504 == 400)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <test_courier_login.TestCourierLogin object at 0x000001F7C90C2B50>\nresponse_expected = {'code': 400, 'message': 'Недостаточно данных для входа'}, data = {'password': None}\nnew_courier_session = {'create_resp': <Response [201]>, 'credentials': {'firstName': 'Lindsey', 'login': 'joseph96'}, 'login_resp': <Response [200]>}\n\n    @allure.title('Система вернёт ошибку, если в данных запроса указать неправильно логин или пароль')\n    @pytest.mark.parametrize(\"response_expected, data\", [\n        (Responses.COURIER_NOT_FOUND, {\"login\": '0000000ef00000'}), # указываем неверный логин\n        (Responses.COURIER_LOGIN_FAILED, {\"login\": ''}), # указываем пустой логин\n        (Responses.COURIER_LOGIN_FAILED, {\"login\": None}), # в запросе авторизации удаляем поле login\n        (Responses.COURIER_NOT_FOUND, {\"password\": '0000000ef00000'}), # указываем неверный пароль\n        (Responses.COURIER_LOGIN_FAILED, {\"password\": ''}), # указываем пустой пароль\n        (Responses.COURIER_LOGIN_FAILED, {\"password\": None}) # в запросе авторизации удаляем поле password -\n                                                            # данный тест не проходит, тк сервер не возвращает ожидаемый ответ с ошибкой (результат 504 Gateway time out)\n    ])\n    def test_courier_creation_scenario_with_invalid_logins(self, response_expected, data, new_courier_session):\n        credentials = new_courier_session[\"credentials\"]\n    \n        keys = list(credentials.keys())\n        for key in keys:\n            if key in data:\n                if data[key] == None:\n                    del credentials[key]\n                else:\n                    credentials[key] = data[key]\n    \n        login_resp = self.courier_api.login(credentials)\n    \n>       assert login_resp.status_code == response_expected['code'] and login_resp.json() == response_expected\nE       assert (504 == 400)\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_courier_login.py:46: AssertionError"}, "parameters": [{"name": "response_expected", "value": "{'code': 400, 'message': 'Недостаточно данных для входа'}"}, {"name": "data", "value": "{'password': None}"}], "start": 1758314309443, "stop": 1758314369542, "uuid": "595828dd-65cf-4b14-8e77-6cda0e438ce4", "historyId": "369029535643715fd2f30f3544d236b4", "testCaseId": "375d36756d17fe61729a4bc9d5518957", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_creation_scenario_with_invalid_logins", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}