{"name": "Система вернёт ошибку при неверном логине", "status": "passed", "steps": [{"name": "Попытка авторизации с неверным логином", "status": "passed", "start": 1758473562081, "stop": 1758473562191}, {"name": "Проверка ожидаемой ошибки", "status": "passed", "start": 1758473562191, "stop": 1758473562191}], "parameters": [{"name": "login_value", "value": "'0000000ef00000'"}, {"name": "expected_response", "value": "{'code': 404, 'message': 'Учетная запись не найдена'}"}], "start": 1758473562081, "stop": 1758473562192, "uuid": "fef9d8c6-2dfc-4c7b-844b-e3716b91a5db", "historyId": "bb2be80b9251455c4909c9dd502c378a", "testCaseId": "24ae6bddaa108523e16b886f0bd76023", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_with_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "13416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}