{"name": "Система вернёт ошибку при неверном логине", "status": "passed", "steps": [{"name": "Попытка авторизации с неверным логином", "status": "passed", "start": 1758473562542, "stop": 1758473562628}, {"name": "Проверка ожидаемой ошибки", "status": "passed", "start": 1758473562628, "stop": 1758473562628}], "parameters": [{"name": "login_value", "value": "''"}, {"name": "expected_response", "value": "{'code': 400, 'message': 'Недостаточно данных для входа'}"}], "start": 1758473562542, "stop": 1758473562629, "uuid": "7b6f2755-b495-4841-8e8d-aa3185c5392d", "historyId": "1f74fa9537275bab6682e3ff6df13310", "testCaseId": "24ae6bddaa108523e16b886f0bd76023", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_with_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "13416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}