{"name": "Система вернёт ошибку при неверном пароле", "status": "passed", "steps": [{"name": "Попытка авторизации с неверным паролем", "status": "passed", "start": 1758473562933, "stop": 1758473563030}, {"name": "Проверка ожидаемой ошибки", "status": "passed", "start": 1758473563030, "stop": 1758473563030}], "parameters": [{"name": "password_value", "value": "'0000000ef00000'"}, {"name": "expected_response", "value": "{'code': 404, 'message': 'Учетная запись не найдена'}"}], "start": 1758473562933, "stop": 1758473563031, "uuid": "46bf812e-27a1-47b7-8732-5881ddaf20cf", "historyId": "178205d2959600f514781eb816c233d8", "testCaseId": "83ee3d8b7704c3c147d5420c7fb48d7d", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_with_invalid_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "13416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}